import React, { useEffect, useState, useRef } from 'react';
import { useSwarmStore } from '../../store/swarmStore';
import SwarmGraph from '../ui/SwarmGraph';
import { openUrl } from '@tauri-apps/plugin-opener';
import '../../styles/HiveChat.css';

interface HiveChatProps {
  sessionId?: string;
}

export const HiveChat: React.FC<HiveChatProps> = () => {
  const {
    currentSession,
    messages,
    isRunning,
    consensusReached,
    activeAgent,
    executeSwarmAction,
    approveAction,
    rejectAction,
    viewMode,
    setViewMode,
    showDecisionLog,
    setShowDecisionLog,
    language,
    setLanguage,
  } = useSwarmStore();

  const [goalInput, setGoalInput] = useState('');
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to latest message
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleLaunchSwarm = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!goalInput.trim()) return;

    await executeSwarmAction(goalInput);
    setGoalInput('');
  };

    const { recipientEmail } = useSwarmStore.getState();
    const mailtoUrl = `mailto:${recipientEmail}?subject=${encodeURIComponent(reportTitle)}&body=${encodeURIComponent(reportBody.substring(0, 1500))}`;
    
    try {
      await openUrl(mailtoUrl);
    } catch (err) {
      console.error('Failed to open mail client:', err);
      // Fallback: Copy to clipboard
      await navigator.clipboard.writeText(reportBody);
      alert('Your email client could not be opened automatically. The FULL report has been copied to your clipboard—you can now paste it directly into an email.');
    }
  };

  const handleDownloadReport = () => {
    if (!currentSession || messages.length === 0) return;

    const reportTitle = `HiveMind_Report_${currentSession.goal.text.substring(0, 20).replace(/\s+/g, '_')}`;
    const reportBody = `# HiveMind Swarm Report
**Goal:** ${currentSession.goal.text}
**Status:** ${consensusReached ? 'Consensus Reached' : 'Pending'}
**Language:** ${language}
**Timestamp:** ${new Date().toLocaleString()}

## Agent Transcripts

${messages.map(m => `### ${m.agentRole.toUpperCase()} (${m.type})
${m.content}
`).join('\n---\n')}

Generated by HiveMind Swarm Orchestrator.`.trim();

    const blob = new Blob([reportBody], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${reportTitle}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getAgentColor = (role: string) => {
    const colors: Record<string, string> = {
      planner: 'var(--agent-planner)',
      researcher: 'var(--agent-researcher)',
      executor: 'var(--agent-executor)',
      critic: 'var(--agent-critic)',
      creator: 'var(--agent-creator)',
      memory: 'var(--agent-memory)',
      system: 'var(--agent-system)',
      user: 'var(--agent-user)',
    };
    return colors[role] || 'var(--color-text-tertiary)';
  };

  const getAgentBgColor = (role: string) => {
    // Return translucent version of agent color for the bubble
    return `${getAgentColor(role)}15`; // 15 is ~8% opacity in hex
  };

  return (
    <div className="hivechat-container">
      {/* Header */}
      <div className="hivechat-header">
        <div className="hivechat-header-left">
          <h2>HiveMind Swarm</h2>
          <div className="status-indicator">
            <span className={`status-dot ${isRunning ? 'active' : 'idle'}`}></span>
            <span className="status-text">
              {isRunning ? 'Thinking...' : consensusReached ? 'Consensus Reached' : 'Ready'}
            </span>
          </div>
        </div>
        <div className="hivechat-header-right">
          <div className="view-toggle">
            <button 
              className={`toggle-btn ${viewMode === 'chat' ? 'active' : ''}`}
              onClick={() => setViewMode('chat')}
            >
              💬 Chat
            </button>
            <button 
              className={`toggle-btn ${viewMode === 'graph' ? 'active' : ''}`}
              onClick={() => setViewMode('graph')}
            >
              🕸️ Graph
            </button>
          </div>
          <button 
            className={`replay-btn ${showDecisionLog ? 'active' : ''}`}
            onClick={() => setShowDecisionLog(!showDecisionLog)}
            title="View decision transparency log"
          >
            📋 Log
          </button>
          <button 
            className="report-btn"
            onClick={handleDownloadReport}
            disabled={messages.length === 0}
            title="Download full report as Markdown"
          >
            💾 Download
          </button>
          <button 
            className="report-btn"
            onClick={handleSendReport}
            disabled={messages.length === 0}
            title="Send summary by email"
          >
            ✉️ Email
          </button>
        </div>
      </div>

      {/* Visualization Graph */}
      {viewMode === 'graph' && (
        <div className="swarm-graph-overlay">
          <SwarmGraph activeAgent={activeAgent || undefined} />
        </div>
      )}

      {/* Decision Replay Log */}
      {showDecisionLog && (
        <div className="decision-replay-panel">
          <h3>Decision Transparency Log</h3>
          {messages
            .filter(m => m.type === 'output')
            .map(msg => (
              <div key={msg.id} className="decision-item">
                <div className="decision-header">
                  <span className="decision-action">
                    {msg.agentRole}: {msg.content.substring(0, 60)}...
                  </span>
                  <span className="decision-confidence">
                    {msg.confidence}% confident
                  </span>
                </div>
              </div>
            ))}
          {messages.filter(m => m.type === 'output').length === 0 && (
            <p className="empty-sub">No decisions logged yet.</p>
          )}
        </div>
      )}

      {/* Messages Area */}
      <div className="hivechat-messages">
        {messages.length === 0 && !isRunning && (
          <div className="empty-state">
            <p>🐝 HiveMind is ready</p>
            <p style={{ fontSize: '14px', color: 'var(--color-text-secondary)' }}>
              Give your hive a goal and watch the agents debate, critique, and reach consensus.
            </p>
          </div>
        )}

        {messages.map(msg => (
          <div
            key={msg.id}
            className="message"
            style={{
              backgroundColor: getAgentBgColor(msg.agentRole),
              borderLeftColor: getAgentColor(msg.agentRole),
            }}
          >
            <div className="message-header">
              <div className="agent-badge" style={{ color: getAgentColor(msg.agentRole) }}>
                {msg.agentRole.charAt(0).toUpperCase() + msg.agentRole.slice(1)}
              </div>
              <div className="message-meta">
                <span className="message-type">{msg.type}</span>
                {msg.confidence && (
                  <span className="confidence-badge">{msg.confidence}%</span>
                )}
              </div>
              <span className="message-time">
                {new Date(msg.timestamp).toLocaleTimeString()}
              </span>
            </div>
            <div className="message-content" style={{ color: 'var(--text-primary)' }}>
              {msg.content}
            </div>
          </div>
        ))}

        {isRunning && (
          <div className="message thinking">
            <div className="agent-badge">🤖</div>
            <div className="thinking-dots">
              <span></span><span></span><span></span>
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Approval Gate */}
      {consensusReached && !isRunning && (
        <div className="approval-gate">
          <div className="approval-content">
            <h3>✓ Consensus Reached</h3>
            <p>The swarm has evaluated the goal and reached agreement. Review above and approve to proceed.</p>
            <div className="approval-buttons">
              <button
                className="btn-approve"
                onClick={() => approveAction('auto-action-1')}
              >
                ✓ Approve & Execute
              </button>
              <button
                className="btn-reject"
                onClick={() => rejectAction('auto-action-1', 'User requested revision')}
              >
                ✗ Revise Plan
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Input Area */}
      <form className="hivechat-input-form" onSubmit={handleLaunchSwarm}>
        <div className="input-wrapper">
          <div className="language-selector-wrapper">
            <span className="language-label">🌐 Lang:</span>
            <select 
              className="language-select"
              value={language}
              onChange={(e) => setLanguage(e.target.value)}
              disabled={isRunning}
            >
              <option value="English">English</option>
              <option value="Arabic">العربية</option>
              <option value="French">Français</option>
              <option value="Spanish">Español</option>
              <option value="German">Deutsch</option>
              <option value="Chinese">中文</option>
              <option value="Japanese">日本語</option>
              <option value="Russian">Русский</option>
            </select>
          </div>
          <input
            type="text"
            placeholder="Give your hive a goal…"
            value={goalInput}
            onChange={e => setGoalInput(e.target.value)}
            disabled={isRunning}
            className="goal-input"
          />
          <button
            type="submit"
            disabled={isRunning || !goalInput.trim()}
            className="launch-btn"
          >
            {isRunning ? '⟳ Thinking' : '▶ Launch →'}
          </button>
        </div>
      </form>
    </div>
  );
};

export default HiveChat;
